export interface GetAllSupplementarySummariesInput {
  filter:string;
  docId:number;
  supplementaryInvoiceNoFilter:string;
  maxSupplementaryInvoiceDateFilter:Date;
  minSupplementaryInvoiceDateFilter:Date;
  maxContractFromDateFilter:Date;
  minContractFromDateFilter:Date;
  maxContractDateFilter:Date;
  minContractDateFilter:Date;
  maxApprovalDateFilter:Date;
  minApprovalDateFilter:Date;
  maxImplementationDateFilter:Date;
  minImplementationDateFilter:Date;
  maxBuyerApprovedTimeFilter:Date;
  minBuyerApprovedTimeFilter:Date;
  maxBuyerRejectedTimeFilter:Date;
  minBuyerRejectedTimeFilter:Date;
  minAccountApprovedTimeFilter:Date;
  maxAccountApprovedTimeFilter:Date;
  maxPaymentApprovedTimeFilter:Date;
  maxAccountRejectedTimeFilter:Date;
  minAccountRejectedTimeFilter:Date;
  minPaymentApprovedTimeFilter:Date;
  maxPaymentRejectedTimeFilter:Date;
  minPaymentRejectedTimeFilter:Date;
  maxGRNQtyFilter:number;
  minGRNQtyFilter:number;
  maxOldValueFilter:number;
  minOldValueFilter:number;
  maxNewValueFilter:number;
  minNewValueFilter:number;
  maxDeltaFilter:number;
  minDeltaFilter:number;
  maxTotalFilter:number;
  minTotalFilter:number;
  maxVersionNoFilter:number;
  minVersionNoFilter:number;
  maxAccountedValueFilter:number;
  minAccountedValueFilter:number;
  documentStatusFilter:number;
  isApprovedFilter:number;
  buyerApprovalStatusFilter:number;
  buyerApprovalFilter:number;
  maxsupplementaryInvoiceFileIdFilter:number;
  minsupplementaryInvoiceFileIdFilter:number;
  minAnnexureFileIdFilter:number;
  maxAnnexureFileIdFilter:number;
  isRejectedFilter:number;
  accountantApprovalStatusFilter:number;
  paymentApprovalStatusFilter:number;
  paymentApprovalFilter:number;
  contractNoFilter:string;
  plantCodeFilter:string;
  buyerEmailAddressFilter:string;
  buyerRemarksFilter:string;
  accountantNameFilter:string;
  accountantEmailAddressFilter:string;
  sccountRemarksFilter:string;
  payerNameFilter:string;
  payerEmailAddressFilter:string;
  paymentRemarksFilter:string;
  partPartNoFilter:string;
  buyerNameFilter:string;
  supplierNameFilter:string;
  buyerIds: number[];
  supplierIds: number[];
  partIds: number[];
  supplementaryId: number;
  partid: number;
  buyerid: number;
  supplierid: number;
  invoicetype: number;
  queryraisedactive: number;
}
