import { DocumentStatus,SupplementaryStatus } from '../../../enum'

export interface SupplementarySummaryDto {
  id:number,
  supplementaryInvoiceNo:string;
    buyerRemarks:string;
    buyerName:string;
    accountantEmailAddress:string;
    paymentApprovedTime:string;
    paymentRejectedTime:string;
    paymentRemarks:string;
    payerEmailAddress:string;
    accountRemarks:string;
    payerName:string;
    accountantName:string;
    buyerEmailAddress:string;
    supplementaryInvoiceDate:Date;
    contractFromDate:Date;
    contractToDate:Date;
    contractDate:Date;
    approvalDate:Date;
    buyerApprovedTime:Date;
    buyerRejectedTime:Date;
    implementationDate:Date;
    accountApprovedTime:Date;
    accountRejectedTime:Date;
    contractNo:string;
    plantCode:string;
    supplementaryInvoiceFileId:number;
    annexureFileId:number;
    grnQty:number;
    oldValue:number;
    newValue:number;
    delta: number;
    total: number;
    versionNo: number;
    isRejected: boolean;
    isApproved: boolean;
    buyerApproval: boolean;
    paymentApproval: boolean;
    accountedValue: number;
    partId: number;
    buyerId: number;
    supplierId: number;
    documentStatus:DocumentStatus;
    buyerApprovalStatus:DocumentStatus;
    accountantApprovalStatus:DocumentStatus;
    paymentApprovalStatus:DocumentStatus;
    partno:string;
    partdescription:string;
    suppliername:string;
    suppliercode:string;
    annexurefilePath:string;  
    supplementrayfilepath:string;  
    supplementrayfilepath2:string;  
    supplementrayfilepath3:string;  
    supplierRemarks:string;  
    userName:string;  
    fromEmail:string;  
    appURL:string;  
    supplierEmailAddress:string;  
    supplementaryStatus:SupplementaryStatus;  
    iscreditnote:boolean;  
    ishistory:boolean;   
    amendedfrom:number;  
    ageing:number;  
    createtime:Date;  
    accountingDate:Date;  
    annexureVersionNo:number;  
    accoutedPrice:number;  
    accountingNo:string;  
    supplementaryinvoicedatestring:string;  
  }
  