import { EnumCurrency } from '../../../enum'

export interface AnnexureDetailDto {
  invoiceNo:string,
  gRNnumber:string,
  invoiceDate:Date,
contractValidFrom:Date,
contractValidTo:Date,
contractNo:string,
oldValue:number,
newValue:number,
diffValue:number,
qty:number,
total:number,
currency:EnumCurrency,
supplementaryInvoiceNo:string,
supplementaryInvoiceDate:Date,
partId:number,
partdescription:string,
buyerId:number,
supplierId:number,
suppliercode:string,
supplementarysummaryId:number,
partPartNo:string,
buyerName:string,
supplierName:string,
uoM:string,
oldContractNumber:string,
newContractNumber:string,
rejectedQty:string,
basicValue:string,
plant:string,
cbfcpaidamout:number,
versionNo:number,
id:number,
}
  