export default class Stores {
  static AuthenticationStore: string = 'authenticationStore';
  static RoleStore: string = 'roleStore';
  static TenantStore: string = 'tenantStore';
  static UserStore: string = 'userStore';
  static SessionStore: string = 'sessionStore';
  static AccountStore: string = 'accountStore';
  static CBFCdataStore: string = 'cbfcdataStore';
  static BuyerStore: string = 'buyerStore'
  static ProcureStore: string = 'procureStore';
  static SupplierStore: string = 'supplierStore';
  static GRNdataStore: string = 'grndataStore';
  static FilemasterStore: string = 'filemasterStore';
  static SupplementarySummariesStore: string = 'supplementarySummariesStore';
  static AnnexureDetailsStore: string = 'annexureDetailsStore';
  static PartsStore: string = 'partsStore';
  static PlantsStore: string = 'plantsStore';
  static SupplierRaisedQueryStore: string = 'supplierRaisedQueryStore';
  static SupplierRejectionStore: string = 'supplierRejectionStore';
  static DisputesStore: string = 'disputesStore'; 
  static ApprovalWorkflowStore: string = 'approvalWorkflowStore';
}
